[package]
name = "sf-server"
version = "0.1.0"
edition = "2021"

[dependencies]
aho-corasick = "1.1.2"
async-once-cell = "0.5.4"
axum = "0.7.7"
base64 = "0.21.7"
chrono = "0.4.38"
fastrand = "2.0.1"
libaes = "0.7.0"
libsql = "0.6.0"
num-derive = "0.4.2"
num-traits = "0.2.18"
once_cell = "1.19.0"
serde = { version = "1.0.196", features = ["derive"] }
serde_json = "1.0.114"
sf-api = "0.1.1"
sha1 = "0.10.6"
strum = { version = "0.26.1", features = ["derive"] }
thiserror = "2.0.3"
tokio = { version = "1.41.1", features = ["macros", "rt-multi-thread", "fs"] }
tracing-subscriber = "0.3.18"
